name: Auto Label PR based on Changes

on:
  pull_request:
    types: [ready_for_review]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
          ref: ${{ github.head_ref }}
      - name: Set Label based on changes
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.pull_request.number;

            // PRの変更されたファイルを取得
            const files = await github.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: issue_number,
            });

            let labels = new Set();

            for (const file of files.data) {
              if (file.filename.startsWith('src/front/')) {
                labels.add('frontend');
              } else if (file.filename.startsWith('src/back/')) {
                labels.add('backend');
              } else if (file.filename.startsWith('src/api/')) {
                labels.add('api');
              }
            }

            if (labels.size > 0) {
              github.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels: Array.from(labels)
              });
            }
